apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:wfJIkOPbcDDRE6qUL+6JhIETMvWXjLahtyBgvF2MPBU="
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  LOG_CHANNEL: "stack"
  DB_CONNECTION: "pgsql"
#  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: "laratest"
  DB_USERNAME: "myuser"
  DB_PASSWORD: "mypassword"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "database"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
#  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
#  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
#  MONGO_URL: mongodb://mongodb/laratest
  MONGO_DATABASE: laratest

