apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: laratest-schedule
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: schedule
              image: superchairon/laratest_php-cli:latest
              args:
                - /bin/sh
                - -c
                - php artisan schedule:run -vvv
#                - php artisan schedule:run >> /dev/null 2>&1 && while pgrep php > /dev/null; do sleep 1; done
              envFrom:
                - configMapRef:
                    name: special-config
          restartPolicy: OnFailure
