# This file configures the laratest app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laratest-gke-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laratest-cli
  template:
    metadata:
      labels:
        app: laratest-cli
    spec:
      containers:
      - name: laratest-php
        image: superchairon/laratest_php-cli:latest
        imagePullPolicy: "Always"
        envFrom:
          - configMapRef:
              name: special-config
